pipeline:
  - name: read
    params:
      input_file: resources/input_examples/json_demo.json # input file path, support json, jsonl, txt, csv, pdf. See resources/input_examples for examples
      chunk_size: 1024 # chunk size for text splitting
      chunk_overlap: 100 # chunk overlap for text splitting

  - name: build_kg

  - name: partition
    params:
      method: dfs # partition method, support: dfs, bfs, ece, leiden
      method_params:
        max_units_per_community: 1 # atomic partition, one node or edge per community
  - name: generate
    params:
      method: atomic # atomic, aggregated, multi_hop, cot, vqa
      data_format: Alpaca # Alpaca, Sharegpt, ChatML
