read:
  input_file: resources/input_examples/txt_demo.txt  # input file path, support json, jsonl, txt, pdf. See resources/input_examples for examples
split:
  chunk_size: 1024 # chunk size for text splitting
  chunk_overlap: 100 # chunk overlap for text splitting
search: # web search configuration
  enabled: false # whether to enable web search
  search_types: ["google"] # search engine types, support: google, bing, uniprot, wikipedia
quiz_and_judge: # quiz and test whether the LLM masters the knowledge points
  enabled: false
partition: # graph partition configuration
  method: leiden # leiden is a partitioner detection algorithm
  method_params:
    max_size: 20 # Maximum size of communities
    use_lcc: false # whether to use the largest connected component
    random_seed: 42 # random seed for partitioning
generate:
  mode: cot # atomic, aggregated, multi_hop, cot, vqa
  data_format: Sharegpt # Alpaca, Sharegpt, ChatML
