pipeline:
  - name: read
    params:
      input_file: resources/input_examples/search_demo.jsonl # input file path, support json, jsonl, txt, pdf. See resources/input_examples for examples

  - name: search
    params:
      data_sources: [uniprot] # data source for searcher, support: wikipedia, google, uniprot
