pipeline:
  - name: read
    params:
      input_file: resources/input_examples/vqa_demo.json # input file path, support json, jsonl, txt, pdf. See resources/input_examples for examples

  - name: chunk
    params:
        chunk_size: 1024 # chunk size for text splitting
        chunk_overlap: 100 # chunk overlap for text splitting

  - name: build_kg

  - name: partition
    params:
      method: anchor_bfs # partition method
      method_params:
        anchor_type: image # node type to select anchor nodes
        max_units_per_community: 10 # atomic partition, one node or edge per community

  - name: generate
    params:
      method: vqa # atomic, aggregated, multi_hop, cot, vqa
      data_format: ChatML # Alpaca, Sharegpt, ChatML
